### ISSUE TITLE
Fix table layouts

### ISSUE THREAD

**Issue by PRijnbeek** [EHDEN/QueryLibrary#24] opened 2019-07-17 18:44 UTC
I have added a style sheet so the tables look a lot better:

![image](https://user-images.githubusercontent.com/7252105/61402357-3c9d0500-a8d3-11e9-8e88-c36e765d892f.png)

I did notice that in many of the markdown files the tables have a kind of doubles space before the second column in them which make the columns very small. As an example I reformatted G01 have a look. G02 still has this problem.

The are also still a number of files that have not specified the input / output tables. 

Can all of you fix your own queries to make sure the tables are complete and nicely rendered?

Thanks.

**Comment by PRijnbeek** [comment] 2019-07-25 19:52
see the current version here:

https://mi-erasmusmc.shinyapps.io/QueryLibrary/

Please fix your own query layouts then we can publish this also on data.ohdsi.org

**Comment by MaximMoinat** [comment] 2019-08-06 12:24
I have checked some queries after your commit yesterday and could only find 1 other badly formatted table. This is now fixed (CE01, empty table replaced by 'No input').

**Comment by PRijnbeek** [comment] 2019-08-07 10:19
Thanks Maxim.

A lot of the Output and Example Output are still empty and need to be populated. 

Peter

**Comment by PRijnbeek** [comment] 2019-08-23 13:50
I still see the layout issue a lot,e.g. output table of G09

**Comment by MaximMoinat** [comment] 2019-08-23 13:58
Interesting. In the markdown there is no difference between the output table in e.g. [CE01](https://github.com/EHDEN/QueryLibrary/blob/master/inst/shinyApps/QueryLibrary/queries/condition_era/CE01.md) and [CE02](https://github.com/EHDEN/QueryLibrary/blob/master/inst/shinyApps/QueryLibrary/queries/condition_era/CE02.md). However, CE01 is rendered nicely, where CE02 has a very narrow second column. The only difference is that for CE0 it is the first table, and for CE02 it is the second table in the markdown file. Any other ideas what can cause the difference in rendering?

**Comment by MaximMoinat** [comment] 2019-08-23 13:59
Just to make sure we are now talking about the same issue, this is what I observe:
![image](https://user-images.githubusercontent.com/17825660/63597978-eb152380-c5be-11e9-899b-4b77f6f2cb7d.png)

**Comment by PRijnbeek** [comment] 2019-08-23 13:59
Yes this is a tricky thing it has to do with space in the table: 

> I did notice that in many of the markdown files the tables have a kind of doubles space before the second column in them which make the columns very small.

**Comment by PRijnbeek** [comment] 2019-08-23 14:00
Yes that is what I am talking about indeed.

**Comment by PRijnbeek** [comment] 2019-08-23 14:05
That screenshot is not from CE02 though which query is that?

**Comment by MaximMoinat** [comment] 2019-08-23 14:17
The screenshot was from G09. 

I compared CE01 and CE02 more closely and the spaces seem identical. Both have a double space in front of the second column (`|  Field |  Description |`). So at least there must be something else causing this layout issue.

**Comment by MaximMoinat** [comment] 2019-08-23 14:23
Also, I can't reproduce this issue in my local test instance of the query library shiny app. All tables use the full available width if necessary.

**Comment by PRijnbeek** [comment] 2019-08-23 14:23
If you click on the Md files in github it looks also fine.. not clear to me.. seem like some bug in the render function

**Comment by PRijnbeek** [comment] 2019-08-23 14:36
It alsop looks fine at our server:

https://mi-erasmusmc.shinyapps.io/QueryLibrary/

not sure could be older package versions on the OHDSI R server?

**Closed as completed** 2020-07-20 08:36 UTC
